server/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret'

    # Imports views blueprint
    from .views import views
    app.register_blueprint(views, url_prefix='/')

    return app

server/sensors/mfrc522/__init__.py
from .MFRC522 import MFRC522
from .SimpleMFRC522 import SimpleMFRC522

name = "mfrc522"

server/views.py
import os
import json
import random
from flask import Blueprint, redirect, render_template, request, url_for, flash
import socket

# Socket establising connection to web_iot.py script for remote login and remote register rfid

# This function creates a new connection with the server
# it returns the socket being connected
def newConnection():
    # Connecting to server
    soc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    host = "127.0.0.1"
    port = 8000

    try:
        soc.connect((host, port))
    except:
        print('\n' + '\33[41m' + "[ERROR] Connection Error. Cannot connect to server" + '\33[0m' )
        pass
    
    return soc

# This function receives the binary input sent from a client
# It then decodes the message and returns it as a string
# The arguments of this function are connection which is the socket connection and the max buffer size 
def receive_input(connection, max_buffer_size):
    client_input = connection.recv(max_buffer_size)
    decodedInput = client_input.decode("utf8").rstrip()
    return decodedInput

views = Blueprint('views', __name__)

global_username = ""

# Site Routing

# Homepage
@views.route('/')
def index():
    return redirect(url_for('views.login'))

# Dashboard
@views.route('/dashboard', methods=['GET', 'POST'])
def dashboard():
    if request.method == "POST":
        try:
            if "change_pin" in request.form:
                print("Change Pin")
                return redirect(url_for('views.change_pin'))
            elif "generate_otp" in request.form:
                return redirect(url_for('views.generate_otp'))
            elif "remote_unlock" in request.form:
                # Socket to send to request of remotely unlocking door
                 # Socket to send to request of registering RFID
                connection = newConnection() # creata a new socket 
                # Server will reply with 'Success or Failure'
                serverInput = receive_input(connection,max_buffer_size=5120)
                connection.send(b'--Remote Unlock Door--') # let client to go into remoteUnlock function in web_iot.py

                # Server will reply with 'RFID Registered Success!' or 'RFID Registered Failed...'
                serverInput = receive_input(connection,max_buffer_size=5120)
                print('Server Reply:' +'\33[31m' + serverInput + '\33[0m')

            else:
                pass
        except:  
            pass # if any error,such as crashes, we just pass so that whole programme will continue.
        
    return render_template('dashboard.html')

# Login Page
@views.route('/login', methods=["GET", "POST"])
def login():
    error = ""
    if request.method == "POST":
        username = request.form['username']
        password = request.form['password']
        
        data = fetch_data("./server/database/users.json")

        # Check if username exists in db
        for user in data['users']:
            print(user['username'])
            if user['username'] == username:
                if user['password'] == password:

                    # ! Need to transfer username to session
                    global global_username
                    global_username = username
                    return redirect(url_for('views.dashboard'))
                else:
                    error = "Password is incorrect"
                    break
        else:
            error = "Username does not exist"

    return render_template('login.html', error=error)

# Monitor
@views.route('/monitor')
def monitor():
    error = ""

    return render_template('monitor.html')

# Change Pin Page
@views.route('/change_pin', methods=['GET', 'POST'])
def change_pin():
    # Empty error
    error = ""
    if request.method == 'POST':
        new_pin = request.form['new_pin']
        new_pin2 = request.form['new_pin2']
        if new_pin == new_pin2 and len(new_pin) == 4:
            # Redirect to dashboard
            flash("Pin changed successfully", "success")

            upload_data("./server/database/password.txt", int(new_pin))

            return redirect(url_for('views.dashboard'))
        elif len(new_pin) != 4:
            error = "Pin must be 4 digits long"
        else:
            # Error message
            error = "Pin did not match"
    return render_template('changePIN.html', error=error)

# Generate OTP
@views.route('/generate_otp')
def generate_otp():
    error = ""

    # Generate OTP that will be keyed into the keypad
    otp = random.randint(1000, 9999)
    upload_data("./server/database/password.txt", int(otp))

    return render_template('generateOTP.html', otp=otp, error=error)

@views.route('/profile')
def profile():
    username = global_username

    return render_template('profile.html', username=username)

# End of Site Routing

# General functions

def fetch_data(filepath: str):

    file_split = os.path.splitext(filepath)
    if file_split[1] == ".json":
        with open(filepath, "r") as f:
            data = json.load(f)
    elif file_split[1] == ".txt":
        with open(filepath, "r") as f:
            data = f.read()
    return data

def upload_data(filepath: str, data: any):
    file_split = os.path.splitext(filepath)
    if file_split[1] == ".json":
        with open(filepath, "w") as f:
            json.dump(data, f, indent=4)
    elif file_split[1] == ".txt":
        with open(filepath, "w") as f:
            f.write(f"{data}")
    return

server/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='style.css')}}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{url_for('views.index')}}">Security System</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="{{url_for('views.dashboard')}}">Home</a>
                    <a class="nav-link" href="{{url_for('views.monitor')}}">Monitor</a>
                    <a class="nav-link" href="{{url_for('views.profile')}}">Profile</a>
                </div>
            </div>
        </div>
    </nav>
    
    {% block content %}
    {% endblock %}

    <!-- jQuery Import -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!-- Bootstrap Import -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>   
    <!-- AXIOS Import -->
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/4467ff6e17.js" crossorigin="anonymous"></script>
</body>
</html>

server/templates/changePIN.html
{% extends "base.html" %}
{% block title %}Main Page{% endblock %}

{% block content %}
<!-- This is used to display the GUI -->
<div class="container">
    <div class="row text-center">
        <h1>Change Personal Identification Number</h1>
        <div class="col-6 mx-auto">
        <form method="POST">
            <div class="row g-3 mt-3">
                <div class="col-6 form-floating">
                    <input 
                    type="password" 
                    onkeypress="return event.charCode>=48 && event.charCode<=57" 
                    name="new_pin" 
                    class="form-control"
                    >
                    <label>New Pin</label>
                </div>
                <div class="col-6 form-floating">
                    <input 
                    type="password" 
                    onkeypress="return event.charCode>=48 && event.charCode<=57" 
                    name="new_pin2" 
                    class="form-control"
                    >
                    <label>Confirm new Pin</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>

        {% if error %}
            <h4 class="my-3 text-danger"><strong>Error:</strong> {{error}}</h4>
        {% endif %}
    </div>
</div>


{% endblock %}

server/templates/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}

{% block content %}

<div class="container text-center w-25">
    <h1>Home</h1>
    <form method="post">
        <div class="row">
            <div class="col-10 mx-auto">
                <!-- Flashing the message taken from the backend -->
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                            <h4 class="bg-success text-light p-2">
                                {{message}}
                            </h4>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
        </div>

        <div class="mt-3">
            <div class="row mb-2">
                <input type="submit" name="change_pin" value="Change PIN">
            </div>
            <div class="row mb-2">
                <input type="submit" name="generate_otp" value="Generate OTP">
            </div>
            <div class="row mb-2">
                <input type="submit" name="remote_unlock" value="Unlock Remotely">
            </div>
        </div>
    </form>
</div>

{% endblock %}

server/templates/generateOTP.html
{% extends "base.html" %}
{% block title %}Main Page{% endblock %}

{% block content %}
<!-- This is used to display the GUI -->
<!-- This is used to display the GUI -->
<div class="container">
    <div class="row text-center">
        <h1>Generate One Time Password</h1>
        <p>We have generated a one time password below. Please input the password before it expires</p>
        <div class="col-6 mx-auto">
        <form method="POST">
            <div class="row">
                <div class="col-6 mx-auto">
                    <h1>
                        {{otp}}
                    </h1>
                </div>
            </div>
        </form>

        {% if error %}
            <h4 class="my-3 text-danger"><strong>Error:</strong> {{error}}</h4>
        {% endif %}
    </div>
</div>


{% endblock %}

server/templates/index.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}

{% block content %}

<div class="container text-center w-25">
    <h1>Home</h1>
    <form method="post">
        <div class="row">
            <div class="col-6 mx-auto">
                <!-- Flashing the message taken from the backend -->
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                            <h4 class="bg-success text-light p-2">
                                {{message}}
                            </h4>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
        </div>

        <div class="mt-3">
            <div class="row mb-2">
                <input type="submit" name="change_pin" value="Change PIN">
            </div>
            <div class="row mb-2">
                <input type="submit" name="change_rfid" value="Change RFID">
            </div>
            <div class="row mb-2">
                <input type="submit" name="generate_otp" value="Generate OTP">
            </div>
        </div>
    </form>
</div>

{% endblock %}

server/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Login{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='style.css')}}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
    
    <div class="container">
        <div class="row text-center mt-5">
            <h1>Login</h1>
            <div class="col-6 mx-auto ">
            <form method="POST">
                <div class="row g-3 mt-3">
                    <div class="col-12 form-floating">
                        <input type="text" name="username" class="form-control">
                        <label>Username</label>
                    </div>
                    <div class="col-12 form-floating">
                        <input type="password" name="password" class="form-control">
                        <label>Password</label>
                    </div>
                    <div class="col-12">
                        <a href="#" class="float-start">Forgot Password</a>
                        <a href="#" class="float-end">Create Password</a>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
    
            {% if error %}
                <h4><strong>Error:</strong> {{error}}</h4>
            {% endif %}
        </div>
    </div>

    <!-- jQuery Import -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!-- Bootstrap Import -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>   
    <!-- AXIOS Import -->
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/4467ff6e17.js" crossorigin="anonymous"></script>
</body>
</html>

server/templates/monitor.html
{% extends "base.html" %}
{% block title %}Main Page{% endblock %}

{% block content %}
<!-- This is used to display the GUI -->
    <div class="container">
        <h1 class="text-center mb-4">Image Taken from Camera</h1>
        <div class="row mt-5">
            <div class="col-4">
                <h3>Image 1</h3>
                <img class="w-75 mb-5" src="../static/image_upload/picture_1.jpg">
            </div>
            <div class="col-4">
                <h3>Image 2</h3>
                <img class="w-75 mb-5" src="../static/image_upload/picture_2.jpg">
            </div>
            <div class="col-4">
                <h3>Image 3</h3>
                <img class="w-75 mb-5" src="../static/image_upload/picture_3.jpg">
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                <h3>Image 4</h3>
                <img class="w-75 mb-5" src="../static/image_upload/picture_4.jpg">
            </div>
            <div class="col-4">
                <h3>Image 5</h3>
                <img class="w-75 mb-5" src="../static/image_upload/picture_5.jpg">
            </div>
            <div class="col-4">
                <h3>Image 6</h3>
                <img class="w-75 mb-5" src="../static/image_upload/picture_6.jpg">
            </div>
        </div>
    </div>

{% endblock %}

server/templates/profile.html
{% extends "base.html" %}
{% block title %}Main Page{% endblock %}

{% block content %}
<!-- This is used to display the GUI -->
<div class="vh-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-12 col-xl-4">
  
          <div class="card" style="border-radius: 15px;">
            <div class="card-body text-center">
              <div class="mt-3 mb-4">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp"
                  class="rounded-circle img-fluid" style="width: 100px;" />
              </div>
              <h4 class="mb-2">{{ username }}</h4>
              <p class="text-muted mb-4">User<span class="mx-2">|</span> <a
                  href="#!">SecuritySystem.com</a></p>
              <div class="mb-4 pb-2">
                <button type="button" class="btn btn-outline-primary btn-floating">
                  <i class="fab fa-facebook-f fa-lg"></i>
                </button>
                <button type="button" class="btn btn-outline-primary btn-floating">
                  <i class="fab fa-twitter fa-lg"></i>
                </button>
                <button type="button" class="btn btn-outline-primary btn-floating">
                  <i class="fab fa-skype fa-lg"></i>
                </button>
              </div>
              <button type="button" class="btn btn-primary btn-rounded btn-lg">
                Update Details
              </button> 
              <div class="text-center mt-5 mb-2">
                <a type="button" class="btn btn-danger btn-rounded btn-lg" href="{{url_for('views.login')}}">
                    Logout
                </a> 
              </div>
            </div>
          </div>
  
        </div>
      </div>
    </div>
  </div>

{% endblock %}